### PR TITLE
appstream: Add a lot of high quality screenshots

### PR DESCRIPTION
**Pull request by Vanadiae**
Also adds a comment to help finding new ones if needed :)

### CODE REVIEW

**Comment by Vanadiae** [comment]
It seems like appstream only allows ≤ 25 screenshots, so I'll have to drop some of them unfortunately (mainly the one that refers to the same thing, or less high quality ones). :(

**Comment by Vanadiae** [comment]
Will merge if CI passes.

**Comment by violetmage** [comment]
flathub not update?

**Comment by Vanadiae** [comment]
I've asked a flathub admin, which launched a new rebuild. We'll see if that fixes anything…

**Comment by Vanadiae** [comment]
So the new build didn't fix it. But I noticed that upstream flightgear repository already ships a metainfo file, which is preferred over appdata files (got confirmation of that from the flathub admin I talked to), so during all this time the informations shown on flathub.org and in GNOME Software were _not_ the one from our appdata file. So I renamed the appdata file to metainfo, which means it should now be replacing the upstream one, so it should show up fine once https://github.com/flathub/org.flightgear.FlightGear/pull/34 is merged.

**Pull request merged**
