### PR TITLE
update flightgear to 2020.3.6

### PR DESCRIPTION
**Pull request by violetmage**
new stable

new boost stable

update submodules

### CODE REVIEW

**Comment by violetmage** [comment]
test OK

**Comment by violetmage** [comment]
fixes #31

**Comment by violetmage** [comment]
Fixes #31

**Comment by violetmage** [comment]
Fixes #31

**Comment by Vanadiae** [comment]
BTW no need to create an issue just to mark if "Fixes #N" straight away in a MR. Your MR looks good changes-wise, but it seems there's a quite bad bug with buildings:

Capture d’écran de 2021-01-29 22-10-20

Here the plane is top-down on the ground, with the camera showing the ground. The buildings only have a very small height visible, while the rest of it is underground.

This bug seems pretty much a blocker to getting this version merged IMO. Can you reproduce this issue on your side?

**Comment by violetmage** [comment]
flightgear 2020.3.5

parking #256 @ EGLL:
image

**Comment by Vanadiae** [comment]
Ah, yeah that's right, it's already there in the version currently published on flathub so it's not a regression. Then I'm merging this MR, thanks @violetmage for the MR!

**Pull request merged**
