### PR TITLE
update to 2020.3.4

### LINKED ISSUE #25: Segmentation fault on launch (2020.3.3)
Since the flatpak package updated to 2020.3.3, it became impossible to run FlightGear:

```
flatpak run org.flightgear.FlightGear
Gtk-Message: 16:50:34.222: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:50:34.222: Failed to load module "unity-gtk-module"
Gtk-Message: 16:50:34.222: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:50:34.222: Failed to load module "unity-gtk-module"
    0.05 [WARN]:gui        Qt: Session management error: None of the authentication protocols specified are supported
Now checking for plug-in osgPlugins-3.6.5/osgdb_nvtt.so
    4.30 [WARN]:general    Enabling ATI/AMD viewport hack
    4.40 [INFO]:terrasync  Starting automatic scenery download/synchronization to '/home/jzimm/.fgfs/TerraSync'.
/app/bin/flightgear.sh: line 2:     3 Segmentation fault      (core dumped) fgfs --launcher "$@"
```

This happens on both Wayland and X11 sessions. I'm running Ubuntu 20.10.

### PR DESCRIPTION
**Pull request by violetmage**
fixes #25

### CODE REVIEW

**Comment by violetmage** [comment]
am now remember how much am disliking sourceforge...

**Comment by violetmage** [comment]
build is to fail from unseeded mirrors

can not download, so can only copy sha1 on sourceforge page...

**Comment by Vanadiae** [comment]
Thanks for the update, I was about to make it but it was late when I realized there was a new update.

> build is to fail from unseeded mirrors

We'll just do like last time, wait one or two days and try again.

Would it be possible that you also update the boost dependency (it's the only one that has a newer release) ? [tarball url](https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.gz), sha256: `afff36d392885120bcac079148c177d1f6f7730ec3d47233aa51b0afa4db94a5`.

**Comment by Vanadiae** [comment]
Since you were having the crash, can you try the new version with the following commands @violetmage ?

```
flatpak install --user https://dl.flathub.org/build-repo/32442/org.flightgear.FlightGear.flatpakref
flatpak --user run org.flightgear.Flightgear
```

**Comment by violetmage** [comment]
am have already finish testing

is seeming, is good

**Comment by Vanadiae** [comment]
Ok, since you're telling it works then can you squash 04e95706f9e9b7bb25a847da847258fcd29482cd and a88d7e6afe3d97a98e3fe0afa10279150b2e5298 together, and give good descriptive names to all commits please ?

**Comment by violetmage** [comment]
am sorry for delay

have combined commits

:)

**Comment by Vanadiae** [comment]
No worry, you're already pretty fast answering :D I'll merge once CI passes again.

**Comment by violetmage** [comment]
sounding good

am happy can help

**Comment by Vanadiae** [comment]
Thanks again!

**Comment by violetmage** [comment]
of course

:)

**Pull request merged**
