### PR TITLE
Update to 2020.3.9

### PR DESCRIPTION
**Pull request by Vanadiae**
I was suscribed to the sourceforge release RSS so I saw that a new release was available. It seems like [Anitya is watching the RSS too](https://release-monitoring.org/project/9716/), but it must be broken because it "updated" today but hasn't noticed a new version is out. But to report it I need a fedora account, which I don't have, so too bad.

### CODE REVIEW

**Comment by Vanadiae** [comment]
Build failure is expected. Will push new hash sums.

**Comment by Vanadiae** [comment]
Duh, seems like only flightgear-data has a 2020.9 version. No simgear nor main Flightgear tarball. I'll keep this PR opened, and check back in a week or so.

**Comment by violetmage** [comment]
duplicate of #42

**Review by violetmage — APPROVED** [review]
lgtm

**Comment by Vanadiae** [comment]
Can you give the built flatpak a go? I'll try it too tomorrow or the day after if possible to make sure it runs fine enough, before merging the MR.

**Comment by violetmage** [comment]
all working, seem ok

**Comment by Vanadiae** [comment]
So I gave it a go and it looked fine enough. I also almost managed to land on a cargo boat :)

**Pull request merged**
